# Generated by Django 5.0.7 on 2025-02-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_event_is_active_event_max_participants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='phonepe_order_id',
            new_name='razorpay_order_id',
        ),
    ]
